name: magmacore docker

on: workflow_dispatch

jobs:
  magmacore-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Free Disk Space
      uses: ShubhamTatvamasi/free-disk-space-action@master

    - run: ./pull-and-push.sh
